### ISSUE TITLE
Handle Environment Selection False Positive

### ISSUE THREAD

**Issue by AdnaneKhan** [AdnaneKhan/Gato-X#158]
**Describe the bug**

When Gato-X encounters an environment, it uses the REST API to check if the environment has a protection rule. If it does, then it suppresses the finding. Gato-X currently does not _resolve_ environments if it is dynamic based on a context expression, such as the job below.

```
 authorize:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request_target' && github.event.pull_request.draft == false)
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name == 'pull_request_target' && format('fabric-acctest-authorize-pr-{0}', github.event.pull_request.number) || 'fabric-acctest-authorize' }}
      cancel-in-progress: true
    steps:
      - run: true
```

**To Reproduce**

**Expected behavior**

Gato-X should detect if the environment is dynamic and check if protection rules are applied to each. Essentially - if environment is a context expression then gato-x should check them all, and if one has a rule, and the protected environment exists in the expression then it is sufficiently protected.

**Screenshots**

** Environment (please complete the following information):**
- Python Version: [e.g. 3.11]

**Additional context**
